import { z } from "zod";

const envSchema = z.object({
  APP_URL: z.string().url(),
  DATABASE_URL: z.string().default("file:./dev.db"),
  SESSION_SECRET: z.string().default("dev-session-secret"),
  API_KEY_PEPPER: z.string().default("dev-api-key-pepper"),
  STORAGE_BACKEND: z.enum(["local", "s3"]).default("local"),
  STORAGE_LOCAL_ROOT: z.string().optional(),
  STORAGE_S3_BUCKET: z.string().optional(),
  STORAGE_S3_REGION: z.string().default("auto"),
  STORAGE_S3_ENDPOINT: z.string().optional(),
  STORAGE_S3_ACCESS_KEY_ID: z.string().optional(),
  STORAGE_S3_SECRET_ACCESS_KEY: z.string().optional(),
  STORAGE_S3_PREFIX: z.string().default("publishes"),
  STORAGE_S3_FORCE_PATH_STYLE: z
    .enum(["true", "false"])
    .default("false")
    .transform((value) => value === "true"),
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM_EMAIL: z.string().default("mdshare.link <auth@mdshare.link>"),
  RESEND_REPLY_TO: z.string().optional(),
  RESEND_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_WEBHOOK_SECRET_FILE: z.string().optional(),
  STRIPE_PRICE_HOBBY_MONTHLY: z.string().optional(),
  STRIPE_CUSTOMER_PORTAL_CONFIGURATION_ID: z.string().optional(),
  FREE_PUBLISH_TTL_SECONDS: z.coerce.number().default(604800),
  FREE_MAX_SITES: z.coerce.number().default(50),
  FREE_STORAGE_BYTES: z.coerce.number().default(10_737_418_240),
  PAID_STORAGE_BYTES: z.coerce.number().default(107_374_182_400),
  SUPPORT_EMAIL: z.string().default("support@mdshare.link"),
  LOG_LEVEL: z.string().default("debug"),
  NODE_ENV: z.string().default("development"),
});

export const env = envSchema.parse({
  APP_URL: process.env.APP_URL,
  DATABASE_URL: process.env.DATABASE_URL,
  SESSION_SECRET: process.env.SESSION_SECRET,
  API_KEY_PEPPER: process.env.API_KEY_PEPPER,
  STORAGE_BACKEND: process.env.STORAGE_BACKEND,
  STORAGE_LOCAL_ROOT: process.env.STORAGE_LOCAL_ROOT,
  STORAGE_S3_BUCKET: process.env.STORAGE_S3_BUCKET,
  STORAGE_S3_REGION: process.env.STORAGE_S3_REGION,
  STORAGE_S3_ENDPOINT: process.env.STORAGE_S3_ENDPOINT,
  STORAGE_S3_ACCESS_KEY_ID: process.env.STORAGE_S3_ACCESS_KEY_ID,
  STORAGE_S3_SECRET_ACCESS_KEY: process.env.STORAGE_S3_SECRET_ACCESS_KEY,
  STORAGE_S3_PREFIX: process.env.STORAGE_S3_PREFIX,
  STORAGE_S3_FORCE_PATH_STYLE: process.env.STORAGE_S3_FORCE_PATH_STYLE,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_FROM_EMAIL: process.env.RESEND_FROM_EMAIL,
  RESEND_REPLY_TO: process.env.RESEND_REPLY_TO,
  RESEND_WEBHOOK_SECRET: process.env.RESEND_WEBHOOK_SECRET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_WEBHOOK_SECRET_FILE: process.env.STRIPE_WEBHOOK_SECRET_FILE,
  STRIPE_PRICE_HOBBY_MONTHLY: process.env.STRIPE_PRICE_HOBBY_MONTHLY,
  STRIPE_CUSTOMER_PORTAL_CONFIGURATION_ID: process.env.STRIPE_CUSTOMER_PORTAL_CONFIGURATION_ID,
  FREE_PUBLISH_TTL_SECONDS: process.env.FREE_PUBLISH_TTL_SECONDS,
  FREE_MAX_SITES: process.env.FREE_MAX_SITES,
  FREE_STORAGE_BYTES: process.env.FREE_STORAGE_BYTES,
  PAID_STORAGE_BYTES: process.env.PAID_STORAGE_BYTES,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL,
  LOG_LEVEL: process.env.LOG_LEVEL,
  NODE_ENV: process.env.NODE_ENV,
});
